name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  Apple:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: make test
        shell: bash
  SPM:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: swift test
        shell: bash
  Lint:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: swift-format lint
        run: make lint 2>&1 | .github/scripts/format.swift
        shell: bash
